---
title: "forbes"
author: "Widya Rahma"
date: "2/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(plotly)
library(lubridate)
library(glue)
library(tidyverse)
library(stringr)
library(flexdashboard)
```

```{r}
forbes <- read.csv("Forbes-2021-Global-500-Companies-Statistics.csv")

colnames(forbes) = c("Rank","Company", "Country","Sales","Profit","Assets","Market_Value")


forbes <- forbes %>% 
  mutate(Country = as.factor(Country))
```

# Aggregation
```{r}
forbes_america <- forbes %>% 
  filter(Country=="United States") %>% 
  group_by(Company) %>% 
  summarise(Total_Market_Value = mean(Market_Value)) %>% 
  ungroup() %>% 
  mutate(label =glue("Company: {Company}
                    Market Value : {Total_Market_Value} "))

```

```{r}
library(ggthemes)
  plot2 <- ggplot(forbes_america, aes(y = Total_Market_Value,
                    x =  Company, text = label)) +
  geom_bar(stat="identity", fill="Orange1", alpha=.6, width=.4)+
  
  theme_pander()+
  labs(x = "Company",
       y = "Total Market Value",
       title = "Forbes Top United States Company") 

  ggplotly(plot2,tooltip="text")
  
 output$plot_8 <- renderPlotly({
    
    
    forbes_america <- forbes %>% 
      filter(Country=="United States") %>% 
      group_by(Company) %>% 
      summarise(Total_Market_Value = mean(Market_Value)) %>% 
      ungroup() %>% 
      mutate(label =glue("Company: {Company}
                    Market Value : {Total_Market_Value} "))
    
    plot8 <- ggplot(forbes_america, aes(y = Total_Market_Value,
                                        x =  Company, text = label)) +
      geom_bar(stat="identity", fill="red1", alpha=.6, width=.4)+
      
      theme_light()+
      theme(axis.text.x=element_text(angle = 45, vjust = 0.5))+
      labs(x = NULL,
           y = NULL,
           title = paste("Total Market Value Forbes Version")) 
    ggplotly(plot8,tooltip="text")
  })


```


```{r}
forbes_count <- head(forbes_clean,20 ) %>% 
  group_by(Country) %>% 
    summarise(Total_Company=n()) %>% 
    arrange(desc(Total_Company)) %>% 
    ungroup()

forbes_count2 <- forbes_count %>% 
  mutate(label = glue("Country : {Country}
                      Total Company: {Total_Company}"))
```


```{r}
plot_forbes <- ggplot(forbes_count2, aes(x=Country, y= Total_Company, text= label)) +
  geom_segment( aes(x= reorder(Country, Total_Company), xend=reorder(Country, Total_Company), y=0, yend=Total_Company), color = "black", lwd = 1.7) +
  geom_point( size=5, color="red", fill=alpha("red", 0.9), alpha=0.9, shape=20, stroke=1) +
  coord_flip()+
  theme_light()
ggplotly(plot_forbes,tooltip = "text")
```

```{r}
average_profit <- head(forbes_clean, 10) %>% 
  group_by(Company, Country) %>% 
  summarise(Max_Sales = max(Sales)) %>% 
  ungroup() %>% 
  arrange(desc(Max_Sales))
average_profit


```

```{r}


forbes_trend <- head(forbes_clean, 10)%>% 
  group_by(Rank) %>% 
    summarise(avg_Sales = round(mean(Sales))) %>% 
  ungroup() %>% 
  mutate(label = glue("Rank: {Rank}
                      Sales: {avg_Sales}"))

plot_forbest2 <- ggplot(forbes_trend, aes(x = Rank, y = avg_Sales)) +
  # group = 1 -> hanya akan buat 1 garis 
  geom_line(group = 2, # text tidak bisa dimasukan ke ggplot/geom kl geom_line
            col = "seagreen") + 
  geom_point( aes(text = label), col = "Red") + 
  labs(title = NULL,
       x = "Rank",
       y = "Average Profit") +

  theme_pander()
ggplotly (plot_forbest2, tooltip = "text")
```


```{r}
forbes4 <- forbes_clean %>% 
  filter(Sales > Assets) %>% 
  group_by(Country) %>% 
  summarise(Total_Profit = sum(Profit)) %>% 
  arrange(desc(Total_Profit)) %>% 
  ungroup() 
  


forbes_glue4 <- forbes4 %>% 
    mutate(label = glue ("Country: {Country}
                       Total Profit: {Total_Profit}"))
```

```{r}
  plotf4 <- ggplot(forbes_glue4, aes(y = Total_Profit,
                    x =  reorder(Country, Total_Profit),text =label)) +
  geom_bar(stat="identity", fill="blue", alpha=1, width=.4)+
  coord_flip()+
  theme_minimal()+
  labs(x = NULL,
       y = "Total Profit",
       title = "Forbes Top Country") 

  ggplotly(plotf4, tooltip = "text")
```
```{r}
checkboxGroupInput(inputId, label,
choices, selected, inline)
```

```{r}
hist(forbes_clean$Rank)
```

```{r}

   forbes_america <- forbes_clean %>% 
      filter(Country=="Germany") %>% 
      group_by(Company) %>% 
      summarise(Total_Market_Value = mean(Market_Value)) %>% 
      ungroup() %>% 
      mutate(label =glue("Company: {Company}
                    Market Value : {Total_Market_Value} "))
    
    plot2 <- ggplot(forbes_america, aes(y = Total_Market_Value,
                                     x =  Company, text = label)) +
      geom_bar(stat="identity", fill="red1", alpha=.6, width=.4)+
      
      theme_light()+
      theme(axis.text.x=element_text(angle = 45, vjust = 0.5))+
      labs(x = NULL,
           y = NULL,
           title = paste("Total Market Value Forbes Version")) 
    ggplotly(plot2,tooltip="text")
```

